### ISSUE TITLE
Gradle dependency un-needed

### ISSUE THREAD

**Issue by corjohnson** [googlesamples/android-RenderScriptIntrinsic#2]
Hello, 

In downloading & running the example, I had gradle fail to sync due to the following dependency in the application gradle file:

`compile files('renderscript-v8.jar')`

Commenting out the dependency allowed the app to build and run. I didn't notice any side effects of that, so I think it might be useful to remove that dependency unless there's something I'm not realizing that went wrong by doing so. The repository doesn't have that file which is what creates the issue with the dependency. 

Thanks,

Corey

**Comment by em020** [comment]
same here, please remove this line, it causes trouble to people.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above. Thank you!
